copyright: Copyright &copy; 2024
extra_css:
- assets/css/extra.css
extra_javascript:
- assets/js/extra.js
- https://polyfill.io/v3/polyfill.min.js?features=es6
- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
markdown_extensions:
- pymdownx.highlight
- pymdownx.superfences
- pymdownx.inlinehilite
- pymdownx.tabbed
- pymdownx.arithmatex
- pymdownx.tasklist
- pymdownx.emoji
- admonition
- footnotes
- toc:
    permalink: true
    toc_depth: 3
nav:
- 首页: index.md
- 报告:
  - 日报:
    - ETF市场分析复盘报告: reports/daily/etf_analysis_20250307.md
    - ETF市场分析复盘报告: reports/daily/etf_analysis_20250306.md
plugins:
- search
- git-revision-date-localized:
    fallback_to_build_date: true
    locale: zh
    type: date
- minify:
    minify_html: true
repo_name: stockdata
repo_url: https://github.com/your-username/stockdata
site_author: Jason
site_description: 自动更新的股票数据复盘报告网站
site_name: 股票数据复盘报告
site_url: https://your-username.github.io/stockdata/
theme:
  features:
  - navigation.instant
  - navigation.tracking
  - navigation.expand
  - navigation.indexes
  - navigation.top
  - search.highlight
  - search.share
  - content.code.copy
  icon:
    repo: fontawesome/brands/github
  language: zh
  name: material
  palette:
  - accent: indigo
    media: '(prefers-color-scheme: light)'
    primary: indigo
    scheme: default
    toggle:
      icon: material/brightness-7
      name: 切换到暗色模式
  - accent: indigo
    media: '(prefers-color-scheme: dark)'
    primary: indigo
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: 切换到亮色模式
