name: 构建并部署文档

on:
  push:
    branches: [ main, master ]
    paths:
      - 'reports/**'
      - 'docs_site/**'
  # 允许手动触发工作流
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: 设置 Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material mkdocs-git-revision-date-localized-plugin mkdocs-minify-plugin pymdown-extensions
      
      - name: 创建必要的目录结构
        run: |
          mkdir -p docs_site/docs/reports/daily
          mkdir -p docs_site/docs/reports/weekly
          mkdir -p docs_site/docs/reports/monthly
          mkdir -p docs_site/docs/reports/other
      
      - name: 生成导航
        run: |
          cd docs_site
          python scripts/generate_nav.py
      
      - name: 构建文档
        run: |
          cd docs_site
          mkdocs build
      
      - name: 部署到 GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs_site/site
          branch: gh-pages 