name: 构建并部署文档

on:
  push:
    branches: [ main, master ]
    paths:
      - '**'  # 监听所有文件变化，因为这是独立仓库
  # 允许手动触发工作流
  workflow_dispatch:

# 添加权限设置
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: 设置 Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material mkdocs-git-revision-date-localized-plugin mkdocs-minify-plugin pymdown-extensions
      
      - name: 创建必要的目录结构
        run: |
          mkdir -p docs/reports/daily
          mkdir -p docs/reports/weekly
          mkdir -p docs/reports/monthly
          mkdir -p docs/reports/other
      
      - name: 生成导航
        run: python scripts/generate_nav.py
      
      - name: 构建文档
        run: mkdocs build

      - name: 设置 Pages
        uses: actions/configure-pages@v4

      - name: 上传构建产物
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - name: 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1 